# Generated by Django 5.0.2 on 2025-05-08 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(auto_now_add=True, verbose_name="记录日期"),
                ),
                (
                    "weight",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="体重(kg)",
                    ),
                ),
                (
                    "body_fat",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="体脂率(%)",
                    ),
                ),
                (
                    "muscle_mass",
                    models.FloatField(blank=True, null=True, verbose_name="肌肉量(kg)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "进度记录",
                "verbose_name_plural": "进度记录",
                "ordering": ["-record_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="训练日期")),
                ("duration", models.IntegerField(verbose_name="训练时长(分钟)")),
                (
                    "calories_burned",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="消耗卡路里"
                    ),
                ),
                (
                    "perceived_intensity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="感知强度(1-10)",
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("C", "已完成"),
                            ("P", "部分完成"),
                            ("S", "跳过"),
                            ("F", "未完成"),
                        ],
                        max_length=1,
                        verbose_name="完成状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="训练笔记")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "训练记录",
                "verbose_name_plural": "训练记录",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserGoalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("WL", "减重"),
                            ("MG", "增肌"),
                            ("ST", "力量训练"),
                            ("EN", "耐力训练"),
                            ("MN", "保持健康"),
                        ],
                        max_length=2,
                        verbose_name="目标类型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "target_value",
                    models.FloatField(blank=True, null=True, verbose_name="目标值"),
                ),
                (
                    "achieved",
                    models.BooleanField(default=False, verbose_name="是否达成"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "目标历史",
                "verbose_name_plural": "目标历史",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="出生日期")),
                (
                    "height",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="身高(cm)",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="体重(kg)",
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("S", "久坐（几乎不运动）"),
                            ("L", "轻度活动（每周运动1-3次）"),
                            ("M", "中度活动（每周运动3-5次）"),
                            ("H", "高度活动（每周运动6-7次）"),
                            ("E", "专业运动员级别"),
                        ],
                        max_length=1,
                        verbose_name="活动水平",
                    ),
                ),
                (
                    "training_goal",
                    models.CharField(
                        choices=[
                            ("WL", "减重"),
                            ("MG", "增肌"),
                            ("ST", "力量训练"),
                            ("EN", "耐力训练"),
                            ("MN", "保持健康"),
                        ],
                        max_length=2,
                        verbose_name="训练目标",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[("BG", "初学者"), ("IM", "中级"), ("AD", "高级")],
                        max_length=2,
                        verbose_name="训练经验",
                    ),
                ),
                (
                    "target_weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="目标体重(kg)"
                    ),
                ),
                (
                    "daily_calorie_goal",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="每日卡路里目标"
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, verbose_name="健康状况"),
                ),
                ("injuries", models.TextField(blank=True, verbose_name="受伤史")),
                ("allergies", models.TextField(blank=True, verbose_name="过敏史")),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="是否为会员"),
                ),
                (
                    "premium_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="会员到期日期"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户档案",
                "verbose_name_plural": "用户档案",
            },
        ),
    ]
