# Generated by Django 5.0.2 on 2025-05-08 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="gender",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "久坐（几乎不运动）"),
                    ("L", "轻度活动（每周运动1-3次）"),
                    ("M", "中度活动（每周运动3-5次）"),
                    ("H", "高度活动（每周运动6-7次）"),
                    ("E", "专业运动员级别"),
                ],
                max_length=1,
                null=True,
                verbose_name="活动水平",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[("BG", "初学者"), ("IM", "中级"), ("AD", "高级")],
                max_length=2,
                null=True,
                verbose_name="训练经验",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(250),
                ],
                verbose_name="身高(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="training_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WL", "减重"),
                    ("MG", "增肌"),
                    ("ST", "力量训练"),
                    ("EN", "耐力训练"),
                    ("MN", "保持健康"),
                ],
                max_length=2,
                null=True,
                verbose_name="训练目标",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="体重(kg)",
            ),
        ),
    ]
