# Generated by Django 5.0.2 on 2025-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_userprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "男"), ("F", "女")],
                max_length=1,
                null=True,
                verbose_name="性别",
            ),
        ),
    ]
