# Generated by Django 5.0.2 on 2025-05-09 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardioTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("distance", models.FloatField(verbose_name="跑量(km)")),
                ("pace", models.FloatField(verbose_name="配速(min/km)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardio_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "有氧训练记录",
                "verbose_name_plural": "有氧训练记录",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="NutritionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("protein", models.FloatField(verbose_name="蛋白质(g)")),
                ("carbs", models.FloatField(verbose_name="碳水化合物(g)")),
                ("fat", models.FloatField(verbose_name="脂肪(g)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "营养摄入记录",
                "verbose_name_plural": "营养摄入记录",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StrengthTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("squat", models.FloatField(verbose_name="深蹲重量(kg)")),
                ("bench_press", models.FloatField(verbose_name="卧推重量(kg)")),
                ("deadlift", models.FloatField(verbose_name="硬拉重量(kg)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strength_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "力量训练记录",
                "verbose_name_plural": "力量训练记录",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WaterIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("amount", models.IntegerField(verbose_name="饮水量(ml)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "饮水记录",
                "verbose_name_plural": "饮水记录",
                "ordering": ["-date"],
            },
        ),
    ]
