# Generated by Django 5.0.2 on 2025-05-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutritionrecord",
            name="date",
            field=models.DateField(),
        ),
    ]
