# Generated by Django 5.0.2 on 2025-05-10 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_alter_nutritionrecord_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionrecord",
            name="calories",
            field=models.FloatField(blank=True, null=True, verbose_name="总热量(kcal)"),
        ),
        migrations.CreateModel(
            name="DailyCalorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("bmr", models.FloatField(verbose_name="基础代谢率(kcal)")),
                ("intake", models.FloatField(default=0, verbose_name="热量摄入(kcal)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calorie_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "每日卡路里记录",
                "verbose_name_plural": "每日卡路里记录",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
