# Generated by Django 5.0.2 on 2025-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_nutritionrecord_calories_dailycalorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycalorie",
            name="intake",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="热量摄入(kcal)"
            ),
        ),
    ]
