# Generated by Django 5.0.2 on 2025-05-10 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0004_alter_dailycalorie_intake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutritionrecord",
            name="calories",
        ),
        migrations.CreateModel(
            name="BMRRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("bmr_value", models.FloatField(verbose_name="基础代谢率(kcal)")),
                ("weight", models.FloatField(verbose_name="记录时体重(kg)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bmr_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "基础代谢率记录",
                "verbose_name_plural": "基础代谢率记录",
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="DailyCalorie",
        ),
    ]
