# Generated by Django 5.2.1 on 2025-06-13 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('video_url', models.URLField(verbose_name='视频链接')),
                ('thumbnail_url', models.URLField(verbose_name='缩略图链接')),
                ('category', models.CharField(choices=[('ST', '力量训练'), ('EN', '耐力训练'), ('FL', '柔韧性训练'), ('WT', '减重训练'), ('MG', '增肌训练'), ('RC', '康复训练'), ('BG', '初学者指南')], max_length=2, verbose_name='分类')),
                ('difficulty', models.CharField(choices=[('BG', '初学者'), ('IM', '中级'), ('AD', '高级')], max_length=2, verbose_name='难度')),
                ('duration', models.IntegerField(verbose_name='时长(分钟)')),
                ('equipment_needed', models.CharField(blank=True, max_length=200, verbose_name='所需器材')),
                ('health_conditions', models.CharField(blank=True, max_length=200, verbose_name='适用健康状况')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '健康视频',
                'verbose_name_plural': '健康视频',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False, verbose_name='是否观看')),
                ('liked', models.BooleanField(default=False, verbose_name='是否喜欢')),
                ('saved', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('watch_date', models.DateTimeField(auto_now_add=True, verbose_name='观看时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_interactions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='videos.healthvideo')),
            ],
            options={
                'verbose_name': '用户视频交互',
                'verbose_name_plural': '用户视频交互',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
